---
title: "Scalar-on-Function regressions for the white mold data"
author: "Denis Shah"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    fig_caption: yes
    highlight: tango
    number_sections: true
    theme: cerulean
    toc: yes
    toc_depth: 4
    toc_float: true
    editor_options: 
      chunk_output_type: console
---


```{r setup, include=FALSE, eval=TRUE}
options(digits = 3)
require(knitr)
## options
knitr::opts_chunk$set(eval = TRUE, echo = FALSE, cache = FALSE, warning = FALSE, message = FALSE)
```


```{r Libraries, message=FALSE}
library(tidyverse)
library(refund)

library(grid)
library(gridExtra)
```



```{r Load-the-data}
wm_load <- readr::read_csv(here::here("Data", "data_model_plus_weather_filtered.csv"), show_col_types = FALSE)
```


```{r Data-prep}
# Simplify things. Keep only the weather-related variables and others needed for calculations
wm_data <-
  wm_load %>%
  dplyr::select(subject, date, planting.date, sampling.date, wm, d2m, t2m_mean, t2m_max, t2m_min, st, sp, sm, rh) %>%
  # Do the filtering steps before doing any calculations or feature engineering:
  # wm_load has identical data for each of the sampling dates, which is why there is a filtering step on sampling.date.
  dplyr::group_by(subject) %>% 
  dplyr::filter(sampling.date == max(sampling.date)) %>%
  dplyr::ungroup() %>% 
  # Add the response variable (wm present or absent; binary):
  dplyr::group_by(subject) %>% 
  dplyr::mutate(wm = (mean(wm, na.rm = T) > 0)*1) %>% 
  # wm as a factor:
  dplyr::mutate(wm = factor(wm, levels = c(0, 1))) %>%
  dplyr::ungroup() %>% 
  dplyr::filter(!is.na(wm)) %>% 
  # Calculate dap (as a numeric):
  dplyr::mutate(dap = as.numeric(date - planting.date)) %>%
  # Convert temperatures from Kelvin to degrees Celsius:
  dplyr::mutate(across(d2m:st, ~ .x - 273.15)) %>%
  # dewpoint depression:
  dplyr::mutate(dpd = t2m_mean - d2m) %>%
  # surface pressure in kPa:
  dplyr::mutate(sp = sp/1000) %>%
  # Ratio of soil temperature to soil moisture:
  dplyr::mutate(stsm = st/sm) %>%
  # Difference in max and min temperatures:
  dplyr::mutate(tdiff = t2m_max - t2m_min) %>%
  # estimate GDD (base 0). NB: base 0 is reasonable for snap bean; see the Jenni et al. (2000) paper. I think we want GDD to start accumulating the day after planting date onwards...
  # I use the day after planting, because we don't know exactly what time of the day the field was planted.
  dplyr::mutate(gddi = ifelse(dap <= 0, 0, (t2m_max + t2m_min)*0.5 - 0)) %>%
  dplyr::group_by(subject) %>% 
  # We don't want the gddi column after creating gdd:
  dplyr::mutate(gdd = cumsum(gddi), .keep = "unused") %>%
  dplyr::ungroup() %>%
  # Keep only the columns you need:
  dplyr::select(subject, dap, wm:gdd)
```


```{r understand-dap, eval=FALSE}
# Number of fields:  356
wm_data %>%
  dplyr::distinct(subject) %>%
  nrow()

# Create a tibble with summaries of min(dap) and max(dap) for each subject:
foo <-
  wm_data %>%
  dplyr::group_by(subject) %>%
  # min_dap is -30 for all subjects, but max_dap varies:
  dplyr::summarise(min_dap = min(dap), max_dap = max(dap))

# This tells us the range in dap for each subject
foo %>%
  # Can print the info for all 356 fields:
  # print(n = Inf)
  dplyr::pull(max_dap) %>%
  range() # 50 to 77
  
# Some graphics to help understand max(dap):
foo %>%
  ggplot(., aes(x = max_dap)) +
  geom_histogram(binwidth = 1, fill = "#69b3a2", colour = "black", alpha = 0.8) +
  theme_bw() +
  xlab("Max dap") +
  ylab("Frequency")

# The empirical cdf for max_dap:
foo %>%
  ggplot(., aes(max_dap)) + 
  stat_ecdf(geom = "step") +
  theme_bw() +
  labs(x = "Max dap", y = "ECDF")
```


```{r dap-and-NAs, eval=FALSE}
# Now, later when attempting the scalar-on-function regression, it will complain if there's not enough data (too many NAs) to do anything useful.  Notice that Kaique Alves had filtered to <60 dap.

# Let's examine the amount of NAs in a matrix of the dap data. To do this efficiently, I will create a function.

p.na <- function(mxl) {
  # Calculate the proportion of NAs in a matrix of the dap data
  # Args:
  #  mxl = maximum length of dap
  # Returns:
  #  an estimate of the proportion of NAs in the dap matrix
  #
  m <- matrix(nrow = 356, ncol = length(-30:mxl))
  
  # fill the elements in the matrix
  for(i in 1:nrow(m)) {
    for(j in 1:ncol(m)) {
     z <- seq(from = as.numeric(foo[i, "min_dap"]), to = as.numeric(foo[i, "max_dap"]))
        m[i, j] <- z[j]
    }  # end inner loop
    }  # end outer loop
  
  # Proportion of NAs in the matrix:
  sum(apply(X = is.na(m), MARGIN = 1, FUN = sum))/length(m)
  
} # end function

# Does it work? Yes.
# p.na(mxl = 60)

# Apply the function to varying lengths of the functional part of the data:
yp <- sapply(50:77, p.na)

# And plot:
yp.dat <-
  tibble(dap = 50:77, y = yp) 

yp.dat %>%
  print(n = Inf)

yp.dat %>%
  ggplot(aes(x = dap, y = y)) + 
  geom_point()

# Conclusions:
# Up tp dap = 55, there's very low missing values, i.e. most of the observations were up to at least 55 dap.
# At 60 dap we will have 3.32% NAs in the dap matrix
# At 65 dap, we will have 7.45% NAs in the dap matrix

# However, the functional models will eliminate any row with NA from the data for prediction, so for example will only get 109 predicted values instead of the full set of 356.  Therefore, we have to subset dap to 50 (no missing values)
```


```{r dap-filtered, results='hide'}
# Filter the dataset to dap <= 50:
wm_data_50 <-
  wm_data %>%
  dplyr::filter(dap <= 50)


foo <-
  wm_data_50 %>%
  dplyr::group_by(subject) %>%
  # min_dap is -30 for all subjects, but max_dap is 50 after filtering:
  dplyr::summarise(min_dap = min(dap), max_dap = max(dap))

# This tells us the range in dap for each subject
foo %>%
  # Can print the info for all 356 fields:
  # print(n = Inf)
  dplyr::pull(max_dap) %>%
  range() # 50
```


```{r setup-functional-regression-objects}
# For scalar-on-function regression, I'll be using the pfr function from the refund package.
# Within pfr, we'll be using the lf() function to pass in the formula.
# In lf(), the arguments X and argvals are passed in as matrices, which will allow for different observation times for each subject. That is important, because it is one of the characteristics of the wm data.

# A matrix of the dap:
# Empty matrix. 81 cols because dap runs from -30 to 65:
# length(-30:50)
m.dap <- matrix(nrow = 356, ncol = length(-30:50))

# fill the elements in the matrix
for(i in 1:nrow(m.dap)) {
   for(j in 1:ncol(m.dap)) {
     z <- seq(from = as.numeric(foo[i, "min_dap"]), to = as.numeric(foo[i, "max_dap"]))
        m.dap[i, j] <- z[j]
   }
}

rm(i, j, z)


# Vector of the response:
# NOTE: Binomial responses should be specified as a numeric vector rather than as a matrix or a factor
Y <- 
  wm_data_50 %>%
  dplyr::group_by(subject) %>%
  dplyr::mutate(wm = as.numeric(wm) - 1) %>%
  dplyr::summarise(y = mean(wm, na.rm = TRUE)) %>%
  dplyr::pull(y)

# Vector of dap used:
dap <- c(-30:50)
```


```{r functions}
getX <- function(x) {
  # N x J matrix of the functional predictor 
  # Args:
  #  x = unquoted variable name
  # Returns:
  #  a matrix
  
  .x <- enquo(x)
  
  z <-
    wm_data_50 %>%
    dplyr::select(subject, dap, !!.x) %>%
    tidyr::pivot_wider(id_cols = subject, names_from = dap, names_prefix = "", values_from = !!.x) %>%
    dplyr::select(-subject) %>%
    as.matrix()

  colnames(z) <- NULL

  return(z)
}

fitted.probs <- function(fit) {
  # Plots the fitted probabilities from a scalar-on-function model, faceting by epidemic or non-epidemic
  #
  # Args:
  # fit = a fitted refund pfr object
  #
  # Returns:
  # A ggplot histogram of the fitted probabilities faceted by epidemic status
  
  
# data.frame of the actual epidemic status and the fitted probabilities from the functional regression model  
df <- data.frame(wm = factor(Y, levels = c(0, 1), labels = c("Absent", "Present")),
                 fit = fit$fitted.values)

ggplot(df, aes(x = fit)) +
  geom_histogram(binwidth = 0.01, fill = "grey80", colour = "black") +
  # avoid warning about missing values when setting xlim
  # https://github.com/tidyverse/ggplot2/issues/4083
  coord_cartesian(xlim = c(0, 1)) +
  # xlim(0, 0.5) +
  facet_wrap(~ wm, ncol = 1) +
  xlab("Fitted probability") +
  ylab("Count") +
  theme_bw() +
  theme(axis.title.x = element_text(face = "bold", size = 12),
        axis.text.x  = element_text(size = 9, angle = 0),
        axis.title.y = element_text(size = 12, angle = 90, face = "bold"),
        axis.text.y  = element_text(size = 9))
}


beta.est <- function(fit, argvals) {
  # Plots the estimated beta(t) function and approximate confidence interval
  #
  # Args:
  # fit = a fitted refund pfr object
  # argvals = vector of the evaluation points
  #
  # Returns:
  # A ggplot of the estimated beta(t) function and the approximate confidence intervals
  
  est <- coef(fit, coords = list(argvals), se = TRUE)
  
  df <- data.frame(time = argvals, 
                   bhat = est$value,
                   upper = est$value + 1.96*est$se,
                   lower = est$value - 1.96*est$se)
  
  # Convert to long format for ggplot input:
  # gather superseded. Will work but no longer under active development
  # df.L <- tidyr::gather(df, key = curve, value = value, bhat:lower, factor_key = TRUE)
  df.L <- df %>% 
    tidyr::pivot_longer(cols = bhat:lower, names_to = "curve", values_to = "value") %>% 
    dplyr::mutate(curve = factor(curve, levels = c("bhat", "upper", "lower")))

  # Set the x-axis breaks and labels:
  breaks <- seq(-30, 50, 10)
  labels <- seq(-30, 50, 10)

  ggplot(df.L, aes(x = time, y = value, color = curve, linetype = curve, group = curve)) +
  # scale_linetype_manual(values = c("solid", "dashed", "dashed"), guide = "none") +
  scale_linetype_manual(values = c("solid", "solid", "solid"), guide = "none") +
  scale_colour_manual(values = c("black", "grey80", "grey80"), guide = "none") +
    annotate("rect",ymin = -Inf, ymax = Inf, xmin = 35, xmax = 50, fill = "steelblue", alpha = 0.2) +
  geom_path() +
  geom_hline(aes(yintercept = 0), colour = "grey50") +
  geom_vline(xintercept = 0, color = "gray", linetype = "dashed") +
  theme_bw() +
  scale_x_continuous(name = "Days relative to sowing", breaks = breaks, labels = labels) +
  ylab(expression(bolditalic("\u03B2")*bolditalic((t))) ) +
  theme(axis.title.x = element_text(face = "bold", size = 12),
        axis.text.x  = element_text(size = 9),
        axis.title.y = element_text(size = 12, angle = 90),
        axis.text.y  = element_text(size = 9))
}


plot.roc <- function(fit) {
  require(plotROC)
  # Plots the ROC curve for the model-estimated probabilities
  # Args:
  # fit = a fitted refund pfr object
  #
  # Returns:
  # A ggplot-style graphic of the ROC curve
  
  df <- data.frame(Y, fit = fit$fitted.values)

  
    basicplot <- ggplot(df, aes(d = Y, m = fit)) + geom_roc(labelsize = 2, labelround = 2) 
    # style_roc is supposed to add the diagonal guideline, but it doesn't, hence the geom_abline call
    basicplot + style_roc(guide = TRUE) + geom_abline(intercept = 0, slope = 1) +
      annotate("text", x = .75, y = .25, label = paste("AUC =", round(calc_auc(basicplot)$AUC, 2)), size = 3) +
      theme(axis.title.x = element_text(face = "bold", size = 12),
            axis.text.x  = element_text(size = 9, angle = 0),
            axis.title.y = element_text(size = 12, angle = 90, face = "bold"),
            axis.text.y  = element_text(size = 9))
 }
```


# Environmental variables {.tabset .tabset-fade .tabset-pills}
## Dew point
```{r d2m}
X <- getX(d2m)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit1, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Mean air temperature
```{r t2m_mean}
X <- getX(t2m_mean)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Max air temperature
```{r t2m_max}
X <- getX(t2m_max)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Min air temperature
```{r t2m_min}
X <- getX(t2m_min)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Max - Min air temperature
```{r tdiff}
X <- getX(tdiff)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Dewpoint depression
```{r dpd}
X <- getX(dpd)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Soil temperature
```{r st}
X <- getX(st)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Soil moisture
```{r sm}
X <- getX(sm)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## soil temperature:soil moisture ratio
```{r stsm}
X <- getX(stsm)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Surface pressure
```{r sp}
X <- getX(sp)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Relative humidity
```{r rh}
X <- getX(rh)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```


## Growing degree days
```{r gdd}
X <- getX(gdd)

# Penalized (a data-driven roughness penalty)
fit1 <- pfr(Y ~ lf(X, argvals = m.dap, bs = "ps", k = 81), family = binomial(link = "logit"))

# Plot the estimated beta(t):
# plot(fit3, rug = FALSE)
h1 <- beta.est(fit1, argvals = dap)

# Histogram of the fitted probabilities:
h2 <- fitted.probs(fit1)

# ROC curve:
h3 <- plot.roc(fit1)

# The final graphic:
gridExtra::grid.arrange(h1, h2, h3, layout_matrix = rbind(c(1, 2), c(3, 2)) )
```

